### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by DoongLi** [juliangaal/livox2pointcloud#1]
Hi, I tried catkin_make under ws_livox, livox_ros_driver and livox_ros_driver2 under src, but an error occurred：

CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:305 (message):
  catkin_package() include dir 'include' does not exist relative to
  '/home/doongli/ws_livox/src/livox2pointcloud'
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  livox2pointcloud/CMakeLists.txt:15 (catkin_package)

**Comment by juliangaal** [comment]
Could you please try the fix on branch [fix/catkin_include](https://github.com/juliangaal/livox2pointcloud/tree/fix/catkin_include). I think the `catkin_package()` call is the root of the problem.

**Comment by juliangaal** [comment]
EDIT: now in branch `noetic`. Thanks for reporting! Closing

**Comment by DoongLi** [comment]
Sorry，I forget the specific problem，but I used this code in livox_ros_driver2 environment.
